import{a as v,S as q,i as s}from"./assets/vendor-73qhTu8_.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();async function p(r,o=1){const e={key:"55684410-10358821b17bf14561ffe1031",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15},{data:t}=await v("https://pixabay.com/api/",{params:e});return t}const f=document.querySelector(".gallery"),g=document.querySelector(".loader"),h=document.querySelector(".js-load-more"),S=new q(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const o=r.map(({webformatURL:a,largeImageURL:i,tags:e,likes:t,views:l,comments:C,downloads:w})=>`<li class="gallery-item">
    <a href = "${i}" class = "gallery-link">
    <img src = "${a}" alt = "${e}"/>
    <div class="info-wrapper"> 
    <p><span>likes:</span> ${t}</p>
    <p><span>views:</span> ${l}</p>
    <p><span>comments:</span> ${C}</p>
    <p><span>downloads:</span> ${w}</p>
    </div>
    </a>
  </li>`).join("");f.insertAdjacentHTML("beforeend",o),S.refresh()}function x(){f.innerHTML=""}function u(){g.classList.remove("hidden")}function F(){g.classList.add("hidden")}function b(){h.classList.remove("load-more-hidden")}function d(){h.classList.add("load-more-hidden")}const E=document.querySelector(".form"),P=document.querySelector("input"),m=document.querySelector(".js-load-more");E.addEventListener("submit",W);m.addEventListener("click",$);let n=1,L=15,c="";async function W(r){if(r.preventDefault(),c=P.value.trim().toLocaleLowerCase(),c.length===0){s.warning({message:"Please enter a search query!",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FFFFFF",maxWidth:432});return}n=1,x(),d(),u();try{const o=await p(c,n);console.log(o),o.hits.length>0?(y(o.hits),L<o.totalHits?b():(d(),s.info({message:"We're sorry, but you've reached the end of search results",position:"bottomCenter",backgroundColor:"#4391ea",messageColor:"#FFFFFF",maxWidth:432}))):s.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FFFFFF",maxWidth:432})}catch{s.error({message:"Error fetching data!",position:"topRight",backgroundColor:"#aa5a5a",messageColor:"#6a1818",maxWidth:432})}finally{r.target.reset(),F()}}async function $(){n++,console.log(n),u(),m.disabled=!0,d(),u();try{const r=await p(c,n);y(r.hits),n*L>=r.totalHits?(d(),s.info({message:"We're sorry, but you've reached the end of search results",position:"bottomCenter",backgroundColor:"#4391ea",messageColor:"#FFFFFF",maxWidth:432})):b();const o=document.querySelector(".gallery-item");if(o){const a=o.getBoundingClientRect().height;window.scrollBy({left:0,top:2*a,behavior:"smooth"})}}catch{s.error({message:"Error fetching data!",position:"topRight",backgroundColor:"#aa5a5a",messageColor:"#6a1818",maxWidth:432})}finally{m.disabled=!1,F()}}
//# sourceMappingURL=index.js.map
