import{a as q,S as v,i as l}from"./assets/vendor-73qhTu8_.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();async function f(r,o=1){const e={key:"55684410-10358821b17bf14561ffe1031",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15},{data:t}=await q("https://pixabay.com/api/",{params:e});return t}const g=document.querySelector(".gallery"),h=document.querySelector(".loader"),y=document.querySelector(".js-load-more"),S=new v(".gallery a",{captionsData:"alt",captionDelay:250});function b(r){const o=r.map(({webformatURL:s,largeImageURL:n,tags:e,likes:t,views:i,comments:C,downloads:w})=>`<li class="gallery-item">
    <a href = "${n}" class = "gallery-link">
    <img src = "${s}" alt = "${e}"/>
    <div class="info-wrapper"> 
    <p><span>likes:</span> ${t}</p>
    <p><span>views:</span> ${i}</p>
    <p><span>comments:</span> ${C}</p>
    <p><span>downloads:</span> ${w}</p>
    </div>
    </a>
  </li>`).join("");g.insertAdjacentHTML("beforeend",o),S.refresh()}function x(){g.innerHTML=""}function d(){h.classList.remove("hidden")}function F(){h.classList.add("hidden")}function L(){y.classList.remove("load-more-hidden")}function u(){y.classList.add("load-more-hidden")}const E=document.querySelector(".form"),P=document.querySelector("input"),p=document.querySelector(".js-load-more");E.addEventListener("submit",$);p.addEventListener("click",M);let a=1,m=15,c="";async function $(r){if(r.preventDefault(),c=P.value.trim().toLocaleLowerCase(),c.length===0){l.warning({message:"Please enter a search query!",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FFFFFF",maxWidth:432});return}a=1,x(),u(),d();try{const o=await f(c,a);console.log(o),o.hits.length>0?(b(o.hits),a*m<o.totalHits&&(console.log(o.totalHits/m),L())):l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FFFFFF",maxWidth:432})}catch{l.error({message:"Error fetching data!",position:"topRight",backgroundColor:"#aa5a5a",messageColor:"#6a1818",maxWidth:432})}finally{r.target.reset(),F()}}async function M(){a++,console.log(a),d(),p.disabled=!0,u(),d();try{const r=await f(c,a);b(r.hits),a*m>=r.totalHits?(u(),l.info({message:"We're sorry, but you've reached the end of search results",position:"bottomCenter",backgroundColor:"#4391ea",messageColor:"#FFFFFF",maxWidth:432})):L();const o=document.querySelector(".gallery-item");if(o){const s=o.getBoundingClientRect().height;window.scrollBy({left:0,top:2*s,behavior:"smooth"})}}catch{l.error({message:"Error fetching data!",position:"topRight",backgroundColor:"#aa5a5a",messageColor:"#6a1818",maxWidth:432})}finally{p.disabled=!1,F()}}
//# sourceMappingURL=index.js.map
